export const SET_ACTIVE_CATEGORY_SLUG = 'SET_ACTIVE_CATEGORY_SLUG'
export const GET_CATEGORY_PRODUCTS_ATTEMPT = 'GET_CATEGORY_PRODUCTS_ATTEMPT'
export const GET_CATEGORY_PRODUCTS_SUCCESS = 'GET_CATEGORY_PRODUCTS_SUCCESS'
export const GET_CATEGORY_PRODUCTS_FAIL = 'GET_CATEGORY_PRODUCTS_FAIL'